/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.EmpleadoDAO;
import Entidades.Empleado;
import javax.swing.JOptionPane;

/**
 *
 * @author alex
 */
public class NuevoEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form NuevoEmpleado
     */
    public NuevoEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NIF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idFranquicia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        idNomina = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(4, 4, 10, 10));

        jLabel2.setText("nombre");
        jLabel2.setAlignmentX(6.0F);
        jPanel1.add(jLabel2);
        jPanel1.add(nombre);

        jLabel3.setText("apellido");
        jLabel3.setAlignmentX(6.0F);
        jPanel1.add(jLabel3);

        apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoActionPerformed(evt);
            }
        });
        jPanel1.add(apellido);

        jLabel4.setText("NIF");
        jLabel4.setAlignmentX(6.0F);
        jPanel1.add(jLabel4);
        jPanel1.add(NIF);

        jLabel5.setText("dirección");
        jLabel5.setAlignmentX(6.0F);
        jPanel1.add(jLabel5);
        jPanel1.add(direccion);

        jLabel6.setText("telefono");
        jLabel6.setAlignmentX(6.0F);
        jPanel1.add(jLabel6);
        jPanel1.add(telefono);

        jLabel7.setText("idFranquicia");
        jLabel7.setAlignmentX(6.0F);
        jPanel1.add(jLabel7);
        jPanel1.add(idFranquicia);

        jLabel8.setText("idNomina");
        jLabel8.setAlignmentX(6.0F);
        jPanel1.add(jLabel8);

        idNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNominaActionPerformed(evt);
            }
        });
        jPanel1.add(idNomina);

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoActionPerformed

    private void idNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idNominaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String nombre = this.nombre.getText();
        String apellido = this.apellido.getText();
        String nif = this.NIF.getText();
        String direccion = this.direccion.getText();
        String telefono = this.telefono.getText();
        long idFranquicia = Long.parseLong(this.idFranquicia.getText());
        long idNomina = Long.parseLong(this.idNomina.getText());
        Empleado e = new Empleado(nombre, apellido, nif, direccion, telefono, idFranquicia, idNomina);
        int n = e.validarEmpleado();
        switch(n){
            case 0:
                JOptionPane.showMessageDialog(this, "Perfecto!", "Empleado registrado con exito!", JOptionPane.INFORMATION_MESSAGE);
                EmpleadoDAO.insertarEmpleado(e);
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Error!", "ID no valido", JOptionPane.ERROR_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Error!", "Nombre no valido", JOptionPane.ERROR_MESSAGE);
                break;
            case 3:
                JOptionPane.showMessageDialog(this, "Error!", "Apellidos no validos", JOptionPane.ERROR_MESSAGE);
                break;
            case 4:
                JOptionPane.showMessageDialog(this, "Error!", "NIF no valido", JOptionPane.ERROR_MESSAGE);
                break;
            case 5:
                JOptionPane.showMessageDialog(this, "Error!", "Telefono no valido", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIF;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField idFranquicia;
    private javax.swing.JTextField idNomina;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
