/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.UsuarioDAO;
import Entidades.Usuario;
import Entidades.Utilidades;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author guill
 */
public class panelUsuario extends javax.swing.JFrame {

    /**
     * Creates new form panelUsuario
     */
    private String email;
    private String contrasena;
    private String nombre;
    private String apellido;
    private String nif;
    private String telefono;

    public panelUsuario() {
        initComponents();
    }

    public panelUsuario(String email, String contrasena, String nombre, String apellido, String nif, String telefono) {
        this.email = email;
        this.contrasena = contrasena;
        this.nombre = nombre;
        this.apellido = apellido;
        this.nif = nif;
        this.telefono = telefono;
        initComponents();
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getContrasena() {
        return contrasena;
    }

    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getNif() {
        return nif;
    }

    public void setNif(String nif) {
        this.nif = nif;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public Usuario getUsuarioActual(String emailUsuarioActual) {
        Usuario usuario = UsuarioDAO.selecionarActual(emailUsuarioActual);
        return usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkboxNombre = new javax.swing.JCheckBox();
        checkboxApellidos = new javax.swing.JCheckBox();
        checkboxTelefono = new javax.swing.JCheckBox();
        checkboxEmail = new javax.swing.JCheckBox();
        campoNombre = new javax.swing.JTextField();
        campoApellidos = new javax.swing.JTextField();
        campoNif = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel2ComponentAdded(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Hola, " + this.nombre);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tus datos: ");

        jLabel3.setText("Nombre: ");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("NIF:");

        jLabel6.setText("Telefono:");

        jLabel7.setText("Email:");

        checkboxNombre.setText("Editable");
        checkboxNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxNombreItemStateChanged(evt);
            }
        });

        checkboxApellidos.setText("Editable");
        checkboxApellidos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkboxApellidosStateChanged(evt);
            }
        });

        checkboxTelefono.setText("Editable");
        checkboxTelefono.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkboxTelefonoStateChanged(evt);
            }
        });
        checkboxTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkboxTelefonoMouseClicked(evt);
            }
        });

        checkboxEmail.setText("Editable");
        checkboxEmail.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkboxEmailStateChanged(evt);
            }
        });
        checkboxEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkboxEmailMouseClicked(evt);
            }
        });

        campoNombre.setEnabled(true);
        campoNombre.setEditable(false);
        campoNombre.setText(this.getNombre());

        campoApellidos.setEditable(false);
        campoApellidos.setText(this.getApellido());

        campoNif.setEditable(false);
        campoNif.setText(this.getNif());
        campoNif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNifActionPerformed(evt);
            }
        });

        campoTelefono.setEditable(false);
        campoTelefono.setText(this.getTelefono());

        campoEmail.setEditable(false);
        campoEmail.setText(this.getEmail());
        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });

        jButton1.setText("Cambiar contraseña");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        btnModificar.setText("Modificar campos");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(4, 4, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                    .addComponent(campoNombre))
                                .addComponent(campoNif, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkboxNombre)
                            .addComponent(checkboxApellidos)
                            .addComponent(checkboxTelefono)
                            .addComponent(checkboxEmail))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxNombre)
                    .addComponent(jLabel3)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(checkboxApellidos)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxTelefono)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxEmail))
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inicio", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ver mis bonos", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ver franquicias", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Comprar bonos", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Poner reclamación", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel2ComponentAdded

    }//GEN-LAST:event_jPanel2ComponentAdded

    private void campoNifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNifActionPerformed

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void checkboxTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkboxTelefonoMouseClicked
    }//GEN-LAST:event_checkboxTelefonoMouseClicked

    private void checkboxEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkboxEmailMouseClicked
    }//GEN-LAST:event_checkboxEmailMouseClicked

    private void checkboxNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxNombreItemStateChanged
        if (checkboxNombre.isSelected()) {
            campoNombre.setEditable(true);
        } else {
            campoNombre.setEditable(false);
        }
    }//GEN-LAST:event_checkboxNombreItemStateChanged

    private void checkboxApellidosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkboxApellidosStateChanged
        if (checkboxApellidos.isSelected()) {
            campoApellidos.setEditable(true);
        } else {
            campoApellidos.setEditable(false);
        }
    }//GEN-LAST:event_checkboxApellidosStateChanged

    private void checkboxTelefonoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkboxTelefonoStateChanged
        if (checkboxTelefono.isSelected()) {
            campoTelefono.setEditable(true);
        } else {
            campoTelefono.setEditable(false);
        }
    }//GEN-LAST:event_checkboxTelefonoStateChanged

    private void checkboxEmailStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkboxEmailStateChanged
        if (checkboxEmail.isSelected()) {
            campoEmail.setEditable(true);
        } else {
            campoEmail.setEditable(false);
        }
    }//GEN-LAST:event_checkboxEmailStateChanged

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        String Nombre = this.nombre,
                Apellido = this.apellido,
                Telefono = this.telefono,
                Email = this.email;

        String nuevoNombre = campoNombre.getText(),
                nuevoApellido = campoApellidos.getText(),
                nuevoTelefono = campoTelefono.getText(),
                nuevoEmail = campoEmail.getText();

        if (JOptionPane.showConfirmDialog(this, "Nuevo nombre introducido: " + nuevoNombre + "\n"
                + "Nuevo apellido introducido: " + nuevoApellido + "\n"
                + "\n" + "Nuevo telefono introducido: " + nuevoTelefono + "\n" + "Nuevo email introducido: " + nuevoEmail) == 0) {
            
        if (campoNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Nombre está sin rellenar.", "Error: Introduzca los datos necesarios.", WARNING_MESSAGE);
            evt.consume();
        } else if (campoNombre.getText().length() > 45) {
            JOptionPane.showMessageDialog(this, "El campo Nombre es mayor de 45 carácteres.", "Error: El Nombre es muy largo.", WARNING_MESSAGE);
            evt.consume();
        } else if (campoNombre.getText().matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(this, "El campo Nombre no puede tener numeros.", "Error: El nombre tiene letras.", WARNING_MESSAGE);
            evt.consume();
        } else if (!nuevoNombre.equals(Nombre)) {
            UsuarioDAO.actualizarNombreUsuario(nuevoNombre, this.nif, this.email, this.contrasena);
        }

        if (campoApellidos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Apellido está sin rellenar.", "Error: Introduzca los datos necesarios.", WARNING_MESSAGE);
            evt.consume();
        } else if (campoApellidos.getText().length() > 45) {
            JOptionPane.showMessageDialog(this, "El campo Apellido es mayor de 45 carácteres.", "Error: El apellido es muy largo.", WARNING_MESSAGE);
            evt.consume();
        } else if (campoApellidos.getText().matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(this, "El campo Apellido no puede tener numeros.", "Error: El apellido tiene numeros.", WARNING_MESSAGE);
            evt.consume();
        } else if (!nuevoApellido.equals(Apellido)) {
            UsuarioDAO.actualizarApellidoUsuario(nuevoApellido, this.nif, this.email, this.contrasena);
        }

        if (campoTelefono.getText().length() != 9) {
            JOptionPane.showMessageDialog(this, "El campo Telefono tiene que tener una longitud de 9 carácteres.", "Error: El NIF no tiene una longitud adecuada..", WARNING_MESSAGE);
            evt.consume();
        } else if (!Utilidades.isNumeric(campoTelefono.getText().substring(0, 8))) {
            JOptionPane.showMessageDialog(this, "El campo Telefono tiene que ser solo numeros.", "Error: El Telefono tiene letras.", WARNING_MESSAGE);
            evt.consume();
        } else if (!nuevoTelefono.equals(Telefono)) {
            UsuarioDAO.actualizarTelefonoUsuario(nuevoTelefono, this.nif, this.email, this.contrasena);
        }

        if (campoEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Email no está introducido", "Error: El Email está vacío.", WARNING_MESSAGE);
            evt.consume();
        } else if (UsuarioDAO.comprobarCorreoRepetidoExcepto(nuevoEmail, Nombre)) {
            JOptionPane.showMessageDialog(this, "El email ya existe.", "Error: El Email ya existe.", WARNING_MESSAGE);
            evt.consume();
           
        } else {
            UsuarioDAO.actualizarEmailUsuario(this.getNif(),nuevoEmail, Email, this.contrasena);
            evt.consume();
            Principal p = new Principal();
            JOptionPane.showMessageDialog(this, "El cambio se ha realizado con exito, vuelva a iniciar sesion por favor.", "Exito", INFORMATION_MESSAGE);
            p.setVisible(true);
            this.setVisible(false);
        }
}

    }//GEN-LAST:event_btnModificarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        cambioContrasenaUsuario ccu = new cambioContrasenaUsuario(this, true);
        ccu.setLocationRelativeTo(this);
        ccu.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelUsuario().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNif;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JCheckBox checkboxApellidos;
    private javax.swing.JCheckBox checkboxEmail;
    private javax.swing.JCheckBox checkboxNombre;
    private javax.swing.JCheckBox checkboxTelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
