/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.UsuarioDAO;
import Entidades.Usuario;
import Entidades.Utilidades;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author DAM112
 */
public class registroUsuario extends javax.swing.JDialog {

    /**
     * Creates new form accesoEmpleado
     */
    public registroUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        campoNombre = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        campoNif = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoContrasena = new javax.swing.JPasswordField();
        btnRegistrarse = new javax.swing.JButton();
        btnLimpiarFormulario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Registro de usuario");

        jLabel2.setLabelFor(campoNombre);
        jLabel2.setText("Nombre");

        jLabel3.setLabelFor(campoApellido);
        jLabel3.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Datos personales");

        jLabel5.setLabelFor(campoNif);
        jLabel5.setText("NIF");

        jLabel6.setLabelFor(campoTelefono);
        jLabel6.setText("Telefono");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Datos de Usuario");

        jLabel8.setLabelFor(campoEmail);
        jLabel8.setText("Email");

        jLabel9.setLabelFor(campoContrasena);
        jLabel9.setText("Contraseña ");

        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
        });
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        btnLimpiarFormulario.setText("Limpiar formulario");
        btnLimpiarFormulario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarFormularioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoNif, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoApellido))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1)
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(171, 171, 171)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTelefono))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoContrasena)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiarFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarse)
                    .addComponent(btnLimpiarFormulario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarFormularioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFormularioMouseClicked
        campoApellido.setText("");
        campoContrasena.setText("");
        campoEmail.setText("");
        campoNif.setText("");
        campoNombre.setText("");
        campoTelefono.setText("");
    }//GEN-LAST:event_btnLimpiarFormularioMouseClicked

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked
        
        String Nombre = null, Apellido = null, NIF = null, Telefono = null, Email = null, Password = null;
        
        if (campoNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo Nombre está sin rellenar." ,"Error: Introduzca los datos necesarios.",WARNING_MESSAGE);
            evt.consume();
        } else if (campoNombre.getText().length() > 45){
            JOptionPane.showMessageDialog(this, "El campo Nombre es mayor de 45 carácteres." ,"Error: El Nombre es muy largo.",WARNING_MESSAGE);
            evt.consume();
        } else if (campoNombre.getText().matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(this, "El campo Nombre no puede tener numeros." ,"Error: El nombre tiene letras.",WARNING_MESSAGE);
            evt.consume();
        } else {
            Nombre = campoNombre.getText();
        }
        
        if (campoApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Apellido está sin rellenar." ,"Error: Introduzca los datos necesarios.",WARNING_MESSAGE);
            evt.consume();
        } else if (campoApellido.getText().length() > 45) {
            JOptionPane.showMessageDialog(this, "El campo Apellido es mayor de 45 carácteres." ,"Error: El apellido es muy largo.",WARNING_MESSAGE);
            evt.consume();
        } else if (campoApellido.getText().matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(this, "El campo Apellido no puede tener numeros." ,"Error: El apellido tiene numeros.",WARNING_MESSAGE);
            evt.consume();
        } else {
            Apellido = campoApellido.getText();
        }
        
        if (campoNif.getText().length() != 9) {
            JOptionPane.showMessageDialog(this, "El campo NIF tiene que tener una longitud de 9 carácteres." ,"Error: El NIF no tiene una longitud adecuada..",WARNING_MESSAGE);
            evt.consume();
        } else if (!Utilidades.isNumeric(campoNif.getText().substring(0, 8))) {
            JOptionPane.showMessageDialog(this, "Solo el ultimo dígito del NIF puede ser una letra." ,"Error: Solo ultimo digito puede ser letra",WARNING_MESSAGE);
            evt.consume();
        } else if (!String.valueOf(campoNif.getText().charAt(8)).matches("[a-zA-Z]")) {
            JOptionPane.showMessageDialog(this, "El ultimo dígito del NIF debe de ser una letra." ,"Error: El ultimo digito debe ser una letra",WARNING_MESSAGE);
            evt.consume();
        } else if (UsuarioDAO.comprobarNIF(campoNif.getText()) == true) {
            JOptionPane.showMessageDialog(this, "El NIF ya está en uso." ,"Error: NIF repetido.",WARNING_MESSAGE);
            evt.consume();
        }else {
            NIF = campoNif.getText();
        }
        
        if (campoTelefono.getText().length() != 9) {
            JOptionPane.showMessageDialog(this, "El campo Telefono tiene que tener una longitud de 9 carácteres." ,"Error: El NIF no tiene una longitud adecuada..",WARNING_MESSAGE);
            evt.consume();
        } else if (!Utilidades.isNumeric(campoTelefono.getText().substring(0,8))){
            JOptionPane.showMessageDialog(this, "El campo Telefono tiene que ser solo numeros." ,"Error: El Telefono tiene letras.",WARNING_MESSAGE);
            evt.consume();
        } else {
            Telefono = campoTelefono.getText();
        }
        
        Pattern patron = Pattern.compile("([a-z0-9]+(\\.?[a-z0-9])*)+@(([a-z]+)\\.([a-z]+))+");
        Matcher correo = patron.matcher(campoEmail.getText());
        
        if (campoEmail.getText().isEmpty()) {
          JOptionPane.showMessageDialog(this, "El campo Email no está introducido" ,"Error: El Email está vacío.",WARNING_MESSAGE);
          evt.consume();
        } else if (UsuarioDAO.comprobarCorreo(campoEmail.getText()) == true) {
            JOptionPane.showMessageDialog(this, "El email ya existe." ,"Error: El Email ya existe.",WARNING_MESSAGE);
            evt.consume();
        } else if (correo.find() == true){
            Email = campoEmail.getText();
        } else {
            evt.consume();
        }
        
        if (campoContrasena.getPassword().toString().isEmpty() || campoContrasena.getText().length() < 5) {
            JOptionPane.showMessageDialog(this, "El campo Contraseña tiene que tener una longitud de al menos 5 carácteres." ,"Error: La contraseña no tiene una longitud adecuada..",WARNING_MESSAGE);
            evt.consume();
        } else {
           Password = campoContrasena.getText();
        }
        if (Nombre != null && Apellido != null && NIF != null && Telefono != null && Email != null && Password != null) {
            if (JOptionPane.showConfirmDialog(this, "Nombre introducido: " + Nombre + "\n" + "Apellido introducido: " + Apellido + "\n" + "NIF introducido: " + NIF + "\n" + "Telefono introducido: " + Telefono + "\n" + "Email introducido: " + Email) == 0) {
                Usuario u = new Usuario();
                u.setNombre(Nombre);
                u.setApellidos(Apellido);
                u.setNif(NIF);
                u.setTelefono(Telefono);
                u.setEmail(Email);
                u.setPassword(Password);
                UsuarioDAO.insertarUsuario(u);
                JOptionPane.showMessageDialog(this, "El registro se ha realizado con exito.", "Exito", INFORMATION_MESSAGE);

                this.setVisible(false);
            };
        }        
        

        
    }//GEN-LAST:event_btnRegistrarseMouseClicked

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                registroUsuario dialog = new registroUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiarFormulario;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JPasswordField campoContrasena;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNif;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
